env:
  global:
    - CODECOV_TOKEN: 73c356fe-6254-4e9c-931a-dc4cf7a92a66
language: node_js
node_js:
  - "5"
  - "6"
  - "7"
install: npm install
script:
  - npm run test
cache:
  directories: node_modules
os:
  - linux
  - osx
